version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd FRONTEND
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'FRONTEND/dist/store'
  discard-paths: yes
