version: 0.0
os: linux
files:
  - source: /
      destination: /home/ec2-user/store-backend
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
        timeout: 400
        runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
        timeout: 400
        runas: ec2-user
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user